version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.lamp
    links:
      - db
      - mail
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/consul
    environment:
      POSTGRES_PASSWORD: consul
  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: consul
  pgadmin:
    image: fenglc/pgadmin4:alpine
    links:
      - db
    ports:
      - "5050:5050"
